blank_issues_enabled: false

contact_links:
  - name: 📘 Contributing Guide
    url: https://github.com/GIGCymru/dhcw-software-engineering-handbook/blob/main/CONTRIBUTING.md
    about: How to suggest changes or contribute to the handbook.

  - name: 📜 Code of Conduct
    url: https://github.com/GIGCymru/dhcw-software-engineering-handbook/blob/main/CODE_OF_CONDUCT.md
    about: Expected behaviour when taking part in this project.
    